version: '3.8'

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app-network

  application:
    image: 'smartparking-app:latest'
    build:
      context: .
    container_name: smartparkingapplication
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
